export const portfolioItems = [
    {
        id: 1,
        title: "Butterfly on Plant",
        price: "$150",
        type: "watercolor",
        isFramed: true,
        width: "12\"",
        height: "16\"",
        weight: "1 lb",
        details: "A vibrant depiction of a butterfly resting on a green plant. This piece captures the beauty of nature in a moment of stillness.",
        imageUrls: [
            "https://imgur.com/Jf7BGFz",
            "https://imgur.com/dm26G0X",
        ]
    },
    {
        id: 2,
        title: "Flowing Leaves",
        price: "$120",
        type: "acrylic",
        isFramed: true,
        width: "12\"",
        height: "16\"",
        weight: "1 lb",
        details: "An abstract representation of leaves flowing in the wind. The piece uses soft colors to evoke a sense of calm.",
        imageUrls: ["https://imgur.com/W5n5t32"]
    },
    {
        id: 3,
        title: "Flowering Agave",
        price: "$200",
        type: "pencil",
        isFramed: true,
        width: "12\"",
        height: "16\"",
        weight: "1 lb",
        details: "A detailed portrayal of an agave plant in full bloom. The rich textures bring the desert plant to life.",
        imageUrls: ["https://imgur.com/Qhd1hLy"]
    },
    {
        id: 4,
        title: "Foldy Plant",
        price: "$110",
        type: "pencil",
        isFramed: true,
        width: "12\"",
        height: "16\"",
        weight: "1 lb",
        details: "An artistic interpretation of a plant with folded leaves. The piece plays with light and shadow to create depth.",
        imageUrls: ["https://imgur.com/Kl4KERd"]
    },
    {
        id: 5,
        title: "Mini Agave",
        price: "$90",
        type: "acrylic",
        width: "12\"",
        isFramed: true,
        height: "16\"",
        weight: "1 lb",
        details: "A small yet detailed depiction of a mini agave plant. Perfect for adding a touch of nature to any space.",
        imageUrls: ["https://imgur.com/9isqmJf"]
    },
    {
        id: 6,
        title: "Multi Agave",
        price: "$180",
        type: "watercolor",
        isFramed: true,
        width: "12\"",
        height: "16\"",
        weight: "1 lb",
        details: "A collection of agave plants, each with unique characteristics. The artwork showcases the diversity within the species.",
        imageUrls: ["https://imgur.com/FfHxcHc"]
    },
    {
        id: 7,
        title: "Orchid Beauty",
        price: "$130",
        type: "watercolor",
        isFramed: true,
        width: "12\"",
        height: "16\"",
        weight: "1 lb",
        details: "A delicate portrayal of an orchid in bloom. The soft colors and fine details make this piece a favorite among flower enthusiasts.",
        imageUrls: ["https://imgur.com/BDNzaem"]
    },
    {
        id: 8,
        title: "Owl in the Night",
        price: "$170",
        type: "watercolor",
        isFramed: true,
        width: "12\"",
        height: "16\"",
        weight: "1 lb",
        details: "A mysterious and enchanting depiction of an owl perched in the night. The dark background contrasts with the owl's bright eyes.",
        imageUrls: ["https://imgur.com/JRTVh6J"]
    },
    {
        id: 9,
        title: "Pink Agave",
        price: "$140",
        type: "watercolor",
        isFramed: true,
        width: "12\"",
        height: "16\"",
        weight: "1 lb",
        details: "A stunning representation of a pink agave plant. The unusual color palette makes this piece stand out.",
        imageUrls: ["https://imgur.com/fRRkSgX"]
    },
    {
        id: 10,
        title: "Pink Mini Agave",
        price: "$95",
        type: "acrylic",
        isFramed: true,
        width: "12\"",
        height: "16\"",
        weight: "1 lb",
        details: "A smaller version of the pink agave, this piece is perfect for compact spaces. It retains all the beauty of its larger counterpart.",
        imageUrls: ["https://imgur.com/516aDc0"]
    },
    {
        id: 11,
        title: "Single Flower",
        price: "$80",
        type: "acrylic",
        isFramed: true,
        width: "12\"",
        height: "16\"",
        weight: "1 lb",
        details: "A simple yet elegant piece showcasing a single flower. The focus on one bloom highlights its natural beauty.",
        imageUrls: ["https://imgur.com/TCHRsAY"]
    },
    {
        id: 12,
        title: "Skull Agave",
        price: "$220",
        type: "pencil",
        isFramed: true,
        width: "12\"",
        height: "16\"",
        weight: "1 lb",
        details: "A unique blend of a skull and agave plant, this piece has a dark, edgy vibe. It's perfect for those who appreciate unconventional art.",
        imageUrls: ["https://imgur.com/ZVl7z0q"]
    }
];
